# Changes here will be overwritten by Copier.
_commit: 1.11.15
_src_path: https://github.com/pawamoy/copier-uv.git
author_email: kettleofketchup@gmail.com
author_fullname: KettleOfKetchup
author_username: kettleofketchup
copyright_date: '2026'
copyright_holder: KettleOfKetchup
copyright_holder_email: kettleofketchup@gmail.com
copyright_license: MIT
project_description: Grafana Dashboards that are reusable across multiple projects
    or a good starting point
project_name: grafana-dashboards
python_package_command_line_name: grafana-dashboards
python_package_distribution_name: grafana-dashboards
python_package_import_name: grafana_dashboards
repository_name: grafana-dashboards
repository_namespace: kettleofketchup
repository_provider: github.com

